#include <iostream>
using namespace std;

/* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * Find the sum of all the even-valued terms in the sequence which do not exceed four million.
 */

int main()
{
	unsigned long int fib=0, fibMinOne=1, fibMinTwo=0, sum=0;
	while(fib < 4000000 ) // we start with fib(2), fib(1) is not even, so we do not start sum at 1
	{
		fib = fibMinOne + fibMinTwo;
		fibMinTwo = fibMinOne;
		fibMinOne = fib;
		if(!(fib&1)) sum += fib; // add the even-valued term to the sum

	}
	cout << sum << endl;
	return 0;
}

